### ISSUE TITLE
Unable to add storybook to Phoenix 1.7 rc 1

### ISSUE THREAD

**Issue by derpycoder** [phenixdigital/phx_live_storybook#190]
When I tried to add [phx_live_storybook](https://hexdocs.pm/phx_live_storybook/PhxLiveStorybook.html) dependency to Phoenix 1.7 rc1, I got these compilation errors, along with few warnings.

```elixir
warning: passing a string as a layout template in use options is deprecated, please pass an atom, such as :live instead of "live.html"
  (phoenix_live_view 0.18.3) lib/phoenix_live_view/utils.ex:154: Phoenix.LiveView.Utils.normalize_layout/2
  (phoenix_live_view 0.18.3) lib/phoenix_live_view.ex:493: Phoenix.LiveView."MACRO-__before_compile__"/2
  (elixir 1.14.0) src/elixir_dispatch.erl:224: :elixir_dispatch.expand_macro_fun/7
  (elixir 1.14.0) src/elixir_dispatch.erl:211: :elixir_dispatch.expand_require/6
  (elixir 1.14.0) src/elixir_dispatch.erl:135: :elixir_dispatch.dispatch_require/7
  (elixir 1.14.0) src/elixir_module.erl:398: :elixir_module.expand_callback/6

warning: passing a string as a layout template in use options is deprecated, please pass an atom, such as :live instead of "live.html"
  (phoenix_live_view 0.18.3) lib/phoenix_live_view/utils.ex:154: Phoenix.LiveView.Utils.normalize_layout/2
  (phoenix_live_view 0.18.3) lib/phoenix_live_view.ex:493: Phoenix.LiveView."MACRO-__before_compile__"/2
  (elixir 1.14.0) src/elixir_dispatch.erl:224: :elixir_dispatch.expand_macro_fun/7
  (elixir 1.14.0) src/elixir_dispatch.erl:211: :elixir_dispatch.expand_require/6
  (elixir 1.14.0) src/elixir_dispatch.erl:135: :elixir_dispatch.dispatch_require/7
  (elixir 1.14.0) src/elixir_module.erl:398: :elixir_module.expand_callback/6

== Compilation error in file lib/phx_live_storybook/live/error_view.ex ==
** (CompileError) lib/phx_live_storybook/live/error_view.ex:2: module Phoenix.View is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    (elixir 1.14.0) expanding macro: Kernel.use/2
    lib/phx_live_storybook/live/error_view.ex:2: PhxLiveStorybook.ErrorView (module)
    expanding macro: PhxLiveStorybook.Web.__using__/1
    lib/phx_live_storybook/live/error_view.ex:2: PhxLiveStorybook.ErrorView (module)
    (elixir 1.14.0) expanding macro: Kernel.use/2
could not compile dependency :phx_live_storybook, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phx_live_storybook", update it with "mix deps.update phx_live_storybook" or clean it with "mix deps.clean phx_live_storybook"
```

___

Extra informations:

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.14.0 (compiled with Erlang/OTP 25)

___

https://elixirforum.com/t/phoenix-1-7-0-rc-0-is-out/51625/64?u=derpycoder

**Comment by cblavier** [comment]
Hey, did you try the `main` branch?
I think this has been solved in #170
