### ISSUE TITLE
Slots crash if rendered more than once in a LiveComponent

### ISSUE THREAD

**Issue by ryoung786** [phenixdigital/phx_live_storybook#206]
With a story for a LiveComponent that has a slot, if `update/2` is called and the slot is caused to rendered again, it crashes with the following error:
```
** (BadMapError) expected a map, got: []
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/html_engine.ex:113: Phoenix.LiveView.HTMLEngine.__assigns__/3
    nofile:2: (file)
    (elixir 1.14.1) src/elixir.erl:298: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.1.1) erl_eval.erl:492: :erl_eval.expr/6
    (stdlib 4.1.1) erl_eval.erl:136: :erl_eval.exprs/6
    (lsbissue 0.1.0) lib/lsbissue_web/foo_component.ex:13: anonymous fn/2 in LsbissueWeb.Foo.render/1
```

I tried to create the simplest possible component to demonstrate the problem:

```elixir
defmodule LsbissueWeb.Foo do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~H"""
    <div id={@id}>
      <button phx-target={@myself} phx-click="inc">+</button>
      <%= render_slot(@foo, @counter) %>
    </div>
    """
  end

  def handle_event("inc", _, socket) do
    {:noreply, assign(socket, counter: socket.assigns.counter + 1)}
  end
end
```

```elixir
defmodule Storybook.Components.Foo do
  use PhxLiveStorybook.Story, :live_component

  def component, do: LsbissueWeb.Foo

  def variations do
    [
      %Variation{
        id: :default,
        attributes: %{counter: 1},
        slots: [
          """
          <:foo let={x}>counter: <%= x %></:foo>
          """
        ]
      }
    ]
  end
end
```

https://user-images.githubusercontent.com/122238/209528204-897cfa94-26b0-4b98-bb30-73c0bf7b6957.mov

Here's a small barebones phoenix repo that can reproduce the problem: https://github.com/ryoung786/lsbissue

Let me know if I can help in any way, or if I've missed something obvious and the error is on my end.  Thanks!

**Comment by cblavier** [comment]
Thanks for your detailed report, Ryan!
I'll investigate it later today

**Comment by cblavier** [comment]
This has just been fixed on master, let me know if this is working for you
