### ISSUE TITLE
Unable to make Storybook work!!

### ISSUE THREAD

**Issue by derpycoder** [phenixdigital/phx_live_storybook#208]
I keep seeing these errors:

```elixir
{:phoenix, "~> 1.7.0-rc.0", override: true},
{:phx_live_storybook, git: "https://github.com/phenixdigital/phx_live_storybook.git"}
```
```elixir
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```

```elixir
(PhxLiveStorybook.AssetNotFound) unknown asset %{"asset" => ["css", "app.css"]}
    (phx_live_storybook 0.4.5) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:12: PhxLiveStorybook.AssetNotFoundController.asset/2
    (phx_live_storybook 0.4.5) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:1: PhxLiveStorybook.AssetNotFoundController.action/2
    (phx_live_storybook 0.4.5) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:1: PhxLiveStorybook.AssetNotFoundController.phoenix_controller_pipeline/2
    (phoenix 1.7.0-rc.0) lib/phoenix/router.ex:425: Phoenix.Router.__call__/2
    (derpy_portfolio 0.1.0) lib/derpy_portfolio_web/endpoint.ex:1: DerpyPortfolioWeb.Endpoint.plug_builder_call/2
    (derpy_portfolio 0.1.0) lib/plug/debugger.ex:136: DerpyPortfolioWeb.Endpoint."call (overridable 3)"/2
    (derpy_portfolio 0.1.0) lib/derpy_portfolio_web/endpoint.ex:1: DerpyPortfolioWeb.Endpoint.call/2
    (phoenix 1.7.0-rc.0) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.9.0) /Users/derpycoder/Projects/Web/derpy_portfolio/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/derpycoder/Projects/Web/derpy_portfolio/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/derpycoder/Projects/Web/derpy_portfolio/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

 I see the same error for app.js, fonts.css, 

![Screenshot 2022-12-31 at 12 38 10 PM](https://user-images.githubusercontent.com/25662120/210128583-d73ac30f-97cc-481a-ae07-d7302197d5f3.png)
![Screenshot 2022-12-31 at 12 37 41 PM](https://user-images.githubusercontent.com/25662120/210128588-c785e829-4c7f-49dc-bd11-f0d986f435c2.png)
![Screenshot 2022-12-31 at 12 41 42 PM](https://user-images.githubusercontent.com/25662120/210128619-993f14e9-6f73-4818-99eb-1a00412e09cd.png)

**Comment by gaiabeatrice** [comment]
If you get the dependency from `git` and not a regular release you have to build the assets manually
https://github.com/phenixdigital/phx_live_storybook/issues/84#issuecomment-1248995920

**Comment by cblavier** [comment]
Yes, you need to build the assets with the following task:

```
mix dev.storybook
```
