### ISSUE TITLE
key `:source` not found after upgrading phoenix live view to 1.8.6

### ISSUE THREAD

**Issue by darioghilardi** [phenixdigital/phx_live_storybook#221]
Hello,

first, thanks for this awesome project!

I think I found an issue after upgrading `phoenix_live_view`, it seems that [this PR](https://github.com/phoenixframework/phoenix_live_view/pull/2342) that was merged after the 1.8.2 release breaks the storybook. 

I tested it again using `phx_live_storybook_sample`, here is the exception:
```
# KeyError at GET /storybook/components/buttons/button

Exception:

    ** (KeyError) key :source not found in: [engine: Phoenix.LiveView.HTMLEngine, caller: #Macro.Env&lt;aliases: [{LiveViewEngine, Phoenix.LiveView.Engine}, {HTMLEngine, Phoenix.LiveView.HTMLEngine}, {TemplateHelpers, PhxLiveStorybook.TemplateHelpers}, {Variation, PhxLiveStorybook.Stories.Variation}, {VariationGroup, PhxLiveStorybook.Stories.VariationGroup}], context: nil, context_modules: [PhxLiveStorybook.Rendering.ComponentRenderer], file: "/Users/dario/www/phx_live_storybook/lib/phx_live_storybook/rendering/component_renderer.ex", function: {:render_component_heex, 3}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, **: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, &lt;: 2, &lt;=: 2, ==: 2, ===: 2, =~: 2, &gt;: 2, &gt;=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, binary_slice: 2, binary_slice: 3, bit_size: 1, byte_size: 1, ceil: 1, div: 2, elem: 2, exit: 1, floor: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, ...]}], lexical_tracker: nil, line: 239, macro_aliases: [], macros: [{Kernel, [!: 1, &amp;&amp;: 2, ..: 0, ..: 2, ..//: 3, &lt;&gt;: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, dbg: 0, dbg: 1, dbg: 2, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, ...]}], module: PhxLiveStorybook.Rendering.ComponentRenderer, requires: [Application, Kernel, Kernel.Typespec], ...&gt;]
        (elixir 1.14.2) lib/keyword.ex:595: Keyword.fetch!/2
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/html_engine.ex:165: Phoenix.LiveView.HTMLEngine.init/1
        (eex 1.14.2) lib/eex/compiler.ex:295: EEx.Compiler.compile/2
        (phx_live_storybook 0.4.0) lib/phx_live_storybook/rendering/component_renderer.ex:239: PhxLiveStorybook.Rendering.ComponentRenderer.render_component_heex/3
        (phx_live_storybook 0.4.0) lib/phx_live_storybook/live/story_live.ex:304: anonymous fn/5 in PhxLiveStorybook.StoryLive.render_content/3
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:548: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_comprehension/5
        (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:471: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:521: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.6) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
</summary>

Code:

`lib/keyword.ex`

    No code available.

`lib/phoenix_live_view/html_engine.ex`

    160         substate: subengine.init(opts),
    161         file: Keyword.get(opts, :file, "nofile"),
    162         indentation: Keyword.get(opts, :indentation, 0),
    163         caller: Keyword.fetch!(opts, :caller),
    164         previous_token_slot?: false,
    165&gt;        source: Keyword.fetch!(opts, :source)
    166       }
    167     end
    168   
    169     ## These callbacks return AST
    170   
 ```

I didn't find any bug report related to this but I saw that both the sample and the storybook are pinned on `phoenix_live_view` 1.8.2 so they are both immune. To replicate I just upgraded the dependency on the sample repository.

The exception is generated because in live view an exception is raised on `fetch` when `source` is missing (`source: Keyword.fetch!(opts, :source)`), without raising the exception the storybook works fine.

**Comment by cblavier** [comment]
Hey Dario 👋

Which version of the storybook did you use? Latest 0.4 release or the current main branch?

**Comment by darioghilardi** [comment]
Hi Christian 👋 , 

thanks for the super fast reply.
I tested with `0.4.5` of the storybook and also by pinning the `main` branch, same result for me.

**Comment by cblavier** [comment]
Just fixed it on main, let me know if everything is ok for you Dario.
I will also push an updated version of the sample application in a few minutes

**Comment by darioghilardi** [comment]
It works now 🥳 !
Thanks a lot, will you also make a new release of `phx_live_storybook` soon?

**Comment by cblavier** [comment]
Yes! Within current month
