### ISSUE TITLE
Improve router API

### ISSUE THREAD

**Issue by glennr** [phenixdigital/phx_live_storybook#24]
I'm seeing a 403 error on  GET http://localhost:4000/storybook/assets/js/app.js. 

This results in deeply nested menu items not being expandable:

![image](https://user-images.githubusercontent.com/72130/185391840-6e6a7aba-4ab6-4f12-a667-805212022858.png)

Request details:

```
GET /storybook/assets/js/app.js HTTP/1.1
Host: localhost:4000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:4000/storybook/components/button/icon
Connection: keep-alive
Cookie: NOPE
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
```

Response

```
HTTP/1.1 403 Forbidden
cache-control: max-age=0, private, must-revalidate
content-length: 76286
content-type: text/html; charset=utf-8
cross-origin-window-policy: deny
date: Thu, 18 Aug 2022 11:53:59 GMT
permissions-policy: accelerometer=(),  ambient-light-sensor=(),  autoplay=(),  battery=(),  camera=(),  cross-origin-isolated=(),  display-capture=(),  document-domain=(),  encrypted-media=(),  geolocation=(),  gyroscope=(),  magnetometer=(),  microphone=(),  midi=(),  navigation-override=(self),  payment=(),  picture-in-picture=(),  publickey-credentials-get=(),  screen-wake-lock=(),  sync-xhr=(self),  usb=(),  web-share=(),  xr-spatial-tracking=(),  clipboard-read=(),  clipboard-write=(self),  gamepad=(),  speaker-selection=(),  conversion-measurement=(),  focus-without-user-activation=(),  hid=(),  idle-detection=(),  serial=(),  sync-script=(),  trust-token-redemption=(),  vertical-scroll=()
referrer-policy: strict-origin-when-cross-origin
server: Cowboy
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: FwxuTP1B_mn4B1UAAM4F
x-xss-protection: 1; mode=block
```

Phoenix shows this error page:

```
Plug.CSRFProtection.InvalidCrossOriginRequestError at GET /storybook/assets/js/app.js

security warning: an embedded <script> tag on another site requested protected JavaScript (if you know what you're doing, disable forgery protection for this route)
```

Strangely phoenix is responding `content-type: text/html; charset=utf-8`

but in `lib/phx_live_storybook/templates/layout/root.html.heex`, indeed the correct mime type is set:

```
15:      <script phx-track-static type="text/javascript" src={application_static_path(@conn, path)}></script>
17:    <script type="text/javascript" src={asset_path(@conn, "js/app.js")}></script> 
```

<details>
<summary>

```
Stacktrace
```

</summary>

```
[debug] ** (Plug.CSRFProtection.InvalidCrossOriginRequestError) security warning: an embedded <script> ta
g on another site requested protected JavaScript (if you know what you're doing, disable forgery protecti
on for this route)                                                                                       
    (plug 1.13.6) lib/plug/csrf_protection.ex:392: Plug.CSRFProtection.ensure_same_origin_and_csrf_token!/3                                                                                                       
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3                                
    (plug 1.13.6) lib/plug/conn.ex:1690: Plug.Conn.run_before_send/2                                     
    (plug 1.13.6) lib/plug/conn.ex:450: Plug.Conn.send_file/5                                            
    (plug 1.13.6) lib/plug/static.ex:308: Plug.Static.send_entire_file/3                                 
    (brmbl 0.1.0) BrmblWeb.Router.storybook_assets/2                                                     
    (brmbl 0.1.0) lib/brmbl_web/router.ex:1: BrmblWeb.Router.__pipe_through9__/1                         
    (phoenix 1.6.11) lib/phoenix/router.ex:346: Phoenix.Router.__call__/2                                
    (brmbl 0.1.0) lib/brmbl_web/endpoint.ex:1: BrmblWeb.Endpoint.plug_builder_call/2                     
    (brmbl 0.1.0) lib/brmbl_web/endpoint.ex:3: anonymous fn/3 in BrmblWeb.Endpoint."call (overridable 3)"/2                                                                                                       
    (appsignal 2.1.7) lib/appsignal/instrumentation.ex:10: Appsignal.Instrumentation.instrument/1        
    (brmbl 0.1.0) lib/plug/debugger.ex:136: BrmblWeb.Endpoint."call (overridable 4)"/2                   
    (brmbl 0.1.0) lib/brmbl_web/endpoint.ex:1: BrmblWeb.Endpoint."call (overridable 5)"/2                
    (brmbl 0.1.0) lib/plug/error_handler.ex:80: BrmblWeb.Endpoint.call/2                                 
    (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4  
    (cowboy 2.9.0) /home/g/src/brmbl/app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /home/g/src/brmbl/app/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3                                                                                                      
    (cowboy 2.9.0) /home/g/src/brmbl/app/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3                                                                                              
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
</details>

**Comment by cblavier** [comment]
In your application `router.exs` make sure that `live_storybook` is at the root and not using your application pipeline.

It should be like this: 

```
defmodule PhxLiveStorybookSampleWeb.Router do
  use PhxLiveStorybookSampleWeb, :router
  import PhxLiveStorybook.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PhxLiveStorybookSampleWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/", PhxLiveStorybookSampleWeb do
    pipe_through(:browser)
    live("/", PageLive, :index)
  end

  live_storybook("/storybook",
    otp_app: :phx_live_storybook_sample,
    backend_module: Storybook
  )
end
```

It's one of the breaking changes of 0.3.0. Storybook is no longer inlining its assets in the HTML body but rather serving them with `Plug.Static` (which should not be CSRF protected)

**Comment by glennr** [comment]
Yep, that was my issue. Thanks!!

```
  scope "/", BrmblWeb do
    pipe_through [:browser]

    live_storybook("/storybook",
      otp_app: :brmbl,
      backend_module: BrmblWeb.Storybook
    )
  end
```

**Comment by jderr-mx** [comment]
I had a similar issue but it was a use case where I wanted to put live_storybook inside a router scope. 
I added a Static.Plug in my app's endpoint.ex 
```
# same Plug.Static that is found in the phx_storybook_live `:storybook_assets` pipeline
 plug(Plug.Static,
    at: Path.join("/storybook", "assets"),
    from: :phx_live_storybook,
    only: ~w(css js images favicon),
    gzip: true
  )
```

**Comment by cblavier** [comment]
ok, we might need to make this routine function more modular maybe?

**Comment by jderr-mx** [comment]
Add it as a Plug module maybe?

**Comment by cblavier** [comment]
I will probably let users mount storybook and assets separately in their `router.ex`

```elixir
defmodule PhxLiveStorybookSampleWeb.Router do
  use PhxLiveStorybookSampleWeb, :router

  import PhxLiveStorybook.Router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PhxLiveStorybookSampleWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/" do
    storybook_assets(path: "/storybook/assets")
  end

  scope "/", PhxLiveStorybookSampleWeb do
    pipe_through(:browser)
    get "/", RedirectController, :redirect_to_storybook
    live("/page", PageLive, :index)

    live_storybook("/storybook",
      otp_app: :phx_live_storybook_sample,
      backend_module: Storybook
    )
  end
end
```
