### ISSUE TITLE
Mounting storybook in the root path

### ISSUE THREAD

**Issue by bigardone** [phenixdigital/phx_live_storybook#84]
👋🏼 Hi there! First of all congrats on this fantastic project 😍 🙌🏼 !

I'm using the `main` version and trying to mount the storybook in `/`. However, although following the guides, I cannot make it work since it can't load assets:

```
[debug] ** (PhxLiveStorybook.EntryNotFound) unknown entry ["assets", "js", "components.js"]
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/live/entry_live.ex:42: PhxLiveStorybook.EntryLive.handle_params/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/utils.ex:369: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
    (telemetry 1.1.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:271: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
    (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.plug_builder_call/2
    (phx_storybook 0.1.0) lib/plug/debugger.ex:136: PhxStorybookWeb.Endpoint."call (overridable 3)"/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.call/2
    (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[info] Sent 404 in 22ms
[debug] ** (PhxLiveStorybook.AssetNotFound) unknown asset %{"asset" => ["js", "app.js"]}
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:12: PhxLiveStorybook.AssetNotFoundController.asset/2
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:1: PhxLiveStorybook.AssetNotFoundController.action/2
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/controllers/asset_not_found_controller.ex:1: PhxLiveStorybook.AssetNotFoundController.phoenix_controller_pipeline/2
    (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.plug_builder_call/2
    (phx_storybook 0.1.0) lib/plug/debugger.ex:136: PhxStorybookWeb.Endpoint."call (overridable 3)"/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.call/2
    (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/1090272/190565642-c4588c3f-3bcd-41fc-92cf-eeaa9203d287.png">

Here's the current configuration I'm using:

```elixir
# config/config.exs

# Storybook config
config :phx_storybook, PhxStorybookWeb.Storybook,
  content_path: Path.expand("../storybook", __DIR__),
  css_path: "/assets/css/components.css",
  js_path: "/assets/js/components.js"
```

```elixir
# lib/phx_storybook_web/router.ex

 # ...
  scope "/" do
    storybook_assets()
  end

  scope "/" do
    pipe_through :browser

    live_storybook("/",
      otp_app: :phx_storybook,
      backend_module: PhxStorybookWeb.Storybook
    )
  end

  # ...
```

And here is what my assets folder looks like:

```
assets
├── css
│   ├── app.css
│   └── components.css
├── js
│   ├── app.js
│   ├── components.js
│   └── hooks.js
├── tailwind.config.js
└── vendor
```

Any idea of what is going on? 
Thanks in advance and keep it up!

**Comment by cblavier** [comment]
Hey Ricardo, @jeremylightsmith just faced the same issue yesterday and contributed an addition to the README.

https://github.com/phenixdigital/phx_live_storybook#contributing

It should fix the issue, let me know!

**Comment by dgigafox** [comment]
@cblavier I am getting this issue as well. Since 0.4.0 hasn't been released yet, I tried to import the storybook to our project via:
```
{:phx_live_storybook, git: "https://github.com/phenixdigital/phx_live_storybook.git"}
```

Now since there is this change that storybook doesn't serve assets anymore, our application can't read storybook's css. So following this path `/storybook/assets/css/app.css` will throw me an `unknown asset %{"asset" => ["css", "app.css"]}` error. This makes sense, I guess, because this library does not include the assets now. So how do we import the storybook and at the same time compile its assets?

**Comment by cblavier** [comment]
If your pointing on `git` instead of a local path, you should build assets in your deps folder:

```
  cd deps/phx_live_storybook
  mix deps.get
  npm ci --prefix assets
  mix assets.build
```

**Comment by dgigafox** [comment]
@cblavier But when 0.4.0 is released then we import it via `{:phx_live_storybook, "~> 0.4"}` then should we do that again? Or when released it already includes the assets in priv/static?

**Comment by cblavier** [comment]
Regular release are bundled with assets in priv :)

**Comment by dgigafox** [comment]
Nice. That clears it up for me. Thanks for the prompt response!

**Comment by bigardone** [comment]
Thanks for the responses 🙌🏼 !
I'm almost there. After building the assets manually, it renders the storybook's layout correctly. However, it keeps failing to find my custom component JS and CSS files:

```
Rebuilding...
Done in 216ms.
[info] GET /
[debug] Processing with PhxLiveStorybook.EntryLive.root/2
  Parameters: %{}
  Pipelines: [:browser, :storybook_browser]
[info] Sent 200 in 75ms
[info] GET /assets/js/components.js
[debug] Processing with PhxLiveStorybook.EntryLive.entry/2
  Parameters: %{"entry" => ["assets", "js", "components.js"]}
  Pipelines: [:browser, :storybook_browser]
[info] Sent 404 in 49ms
[debug] ** (PhxLiveStorybook.EntryNotFound) unknown entry ["assets", "js", "components.js"]
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/live/entry_live.ex:42: PhxLiveStorybook.EntryLive.handle_params/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/utils.ex:369: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
    (telemetry 1.1.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:271: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
    (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.plug_builder_call/2
    (phx_storybook 0.1.0) lib/plug/debugger.ex:136: PhxStorybookWeb.Endpoint."call (overridable 3)"/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.call/2
    (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[info] GET /assets/css/components.css
[info] GET /storybook/assets/css/app.css
[info] GET /storybook/assets/js/app.js
[debug] Processing with PhxLiveStorybook.AssetNotFoundController.asset/2
  Parameters: %{"asset" => ["js", "app.js"]}
  Pipelines: [:storybook_assets]
[debug] Processing with PhxLiveStorybook.EntryLive.entry/2
  Parameters: %{"entry" => ["assets", "css", "components.css"]}
  Pipelines: [:browser, :storybook_browser]
[debug] Processing with PhxLiveStorybook.AssetNotFoundController.asset/2
  Parameters: %{"asset" => ["css", "app.css"]}
  Pipelines: [:storybook_assets]
[info] Sent 304 in 2ms
[info] Sent 304 in 2ms
[debug] Phoenix.Router halted in :storybook_assets/2
[debug] Phoenix.Router halted in :storybook_assets/2
[info] Sent 404 in 22ms
[debug] ** (PhxLiveStorybook.EntryNotFound) unknown entry ["assets", "css", "components.css"]
    (phx_live_storybook 0.4.0) lib/phx_live_storybook/live/entry_live.ex:42: PhxLiveStorybook.EntryLive.handle_params/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/utils.ex:369: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
    (telemetry 1.1.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:271: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
    (phoenix_live_view 0.17.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
    (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.plug_builder_call/2
    (phx_storybook 0.1.0) lib/plug/debugger.ex:136: PhxStorybookWeb.Endpoint."call (overridable 3)"/2
    (phx_storybook 0.1.0) lib/phx_storybook_web/endpoint.ex:1: PhxStorybookWeb.Endpoint.call/2
    (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.9.0) /Users/ricardogarciavega/projects/cabify/elixir/phx_storybook/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

The configuration is:

```elixir
# Storybook config
config :phx_storybook, PhxStorybookWeb.Storybook,
  content_path: Path.expand("../storybook", __DIR__),
  css_path: "/assets/css/components.css",
  js_path: "/assets/js/components.js"
```

And I have created the files under `./assets`:

```
❯ tree assets
assets
├── css
│   ├── app.css
│   └── components.css
├── js
│   ├── app.js
│   ├── components.js
│   └── hooks.js
├── tailwind.config.js
└── vendor
```

Do I have to do anything else with these files?

**Comment by cblavier** [comment]
The documentation might be counter-intuitive, I will improve it.

The `css_path` / `js_path` you are passing to `phx_live_storybook` config are remote path (and not local filesystem path).
So make sure that when your start your application, you can reach your assets from your browser with the given path.

I think that the correct settings would be:

```elixir
config :phx_storybook, PhxStorybookWeb.Storybook,
  content_path: Path.expand("../storybook", __DIR__),
  css_path: "/assets/components.css",
  js_path: "/assets/components.js"
```

**Comment by bigardone** [comment]
I finally managed to make it work. Thank you, everybody, for the help 🙌🏼
